# Generated by Django 3.1 on 2020-08-16 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fcuser',
            old_name='register_data',
            new_name='register_date',
        ),
    ]
